// Default player pool — real-style IPL pool for the 10 franchises.
// Photos: deterministic DiceBear avatars (free, no API key).
export type Role = "BAT" | "BOWL" | "AR" | "WK";

export interface SeedPlayer {
  name: string;
  role: Role;
  base_price: number; // crore
  rating: number;     // 60-99
  nationality?: string;
}

export function playerPhoto(name: string): string {
  const url = new URL("https://api.dicebear.com/9.x/avataaars/svg");
  url.searchParams.set("seed", name);
  url.searchParams.set("backgroundType", "gradientLinear");
  url.searchParams.set("backgroundColor", "1e293b,0f172a,1a1f3a");
  return url.toString();
}

// 150-player pool with overseas flagged.
export const SEED_POOL: SeedPlayer[] = [
  // ─── Batters (Indian) ─────────────────────────────────
  { name: "Virat Kohli",        role: "BAT",  base_price: 2,   rating: 95 },
  { name: "Rohit Sharma",       role: "BAT",  base_price: 2,   rating: 93 },
  { name: "Shubman Gill",       role: "BAT",  base_price: 2,   rating: 91 },
  { name: "Yashasvi Jaiswal",   role: "BAT",  base_price: 1.5, rating: 89 },
  { name: "Suryakumar Yadav",   role: "BAT",  base_price: 2,   rating: 92 },
  { name: "Ruturaj Gaikwad",    role: "BAT",  base_price: 1.5, rating: 88 },
  { name: "Tilak Varma",        role: "BAT",  base_price: 1,   rating: 84 },
  { name: "Shreyas Iyer",       role: "BAT",  base_price: 1.5, rating: 87 },
  { name: "Rinku Singh",        role: "BAT",  base_price: 1.5, rating: 85 },
  { name: "Sai Sudharsan",      role: "BAT",  base_price: 1,   rating: 83 },
  { name: "Abhishek Sharma",    role: "BAT",  base_price: 1,   rating: 82 },
  { name: "Devdutt Padikkal",   role: "BAT",  base_price: 0.75,rating: 79 },
  { name: "Prithvi Shaw",       role: "BAT",  base_price: 0.75,rating: 78 },
  { name: "Ishan Kishan",       role: "BAT",  base_price: 1,   rating: 83 },
  { name: "Mayank Agarwal",     role: "BAT",  base_price: 0.75,rating: 78 },
  { name: "Rajat Patidar",      role: "BAT",  base_price: 1,   rating: 82 },
  { name: "Riyan Parag",        role: "BAT",  base_price: 1,   rating: 80 },
  { name: "Priyansh Arya",      role: "BAT",  base_price: 0.5, rating: 76 },

  // ─── Batters (Overseas) ───────────────────────────────
  { name: "Travis Head",        role: "BAT",  base_price: 2,   rating: 91, nationality: "AUS" },
  { name: "Faf du Plessis",     role: "BAT",  base_price: 1.5, rating: 88, nationality: "RSA" },
  { name: "Jos Buttler",        role: "BAT",  base_price: 2,   rating: 93, nationality: "ENG" },
  { name: "Devon Conway",       role: "BAT",  base_price: 1.5, rating: 86, nationality: "NZ"  },
  { name: "Quinton de Kock",    role: "BAT",  base_price: 1.5, rating: 87, nationality: "RSA" },
  { name: "Will Jacks",         role: "BAT",  base_price: 1,   rating: 82, nationality: "ENG" },
  { name: "Phil Salt",          role: "BAT",  base_price: 1.5, rating: 86, nationality: "ENG" },
  { name: "Kane Williamson",    role: "BAT",  base_price: 1.5, rating: 87, nationality: "NZ"  },
  { name: "Heinrich Klaasen",   role: "BAT",  base_price: 2,   rating: 90, nationality: "RSA" },
  { name: "Shimron Hetmyer",    role: "BAT",  base_price: 1,   rating: 83, nationality: "WI"  },

  // ─── Wicket-keepers ───────────────────────────────────
  { name: "MS Dhoni",           role: "WK",   base_price: 2,   rating: 90 },
  { name: "Rishabh Pant",       role: "WK",   base_price: 2,   rating: 92 },
  { name: "Sanju Samson",       role: "WK",   base_price: 1.5, rating: 88 },
  { name: "KL Rahul",           role: "WK",   base_price: 2,   rating: 89 },
  { name: "Dinesh Karthik",     role: "WK",   base_price: 1,   rating: 80 },
  { name: "Jitesh Sharma",      role: "WK",   base_price: 0.75,rating: 79 },
  { name: "Dhruv Jurel",        role: "WK",   base_price: 0.75,rating: 80 },
  { name: "N Jagadeesan",       role: "WK",   base_price: 0.5, rating: 75 },
  { name: "Prabhsimran Singh",  role: "WK",   base_price: 0.75,rating: 78 },
  { name: "Wriddhiman Saha",    role: "WK",   base_price: 0.5, rating: 76 },

  // ─── All-rounders (Indian) ────────────────────────────
  { name: "Hardik Pandya",      role: "AR",   base_price: 2,   rating: 91 },
  { name: "Ravindra Jadeja",    role: "AR",   base_price: 1.5, rating: 89 },
  { name: "Axar Patel",         role: "AR",   base_price: 1.5, rating: 86 },
  { name: "Krunal Pandya",      role: "AR",   base_price: 1,   rating: 80 },
  { name: "Washington Sundar",  role: "AR",   base_price: 1,   rating: 82 },
  { name: "Nitish Kumar Reddy", role: "AR",   base_price: 1,   rating: 83 },
  { name: "Shivam Dube",        role: "AR",   base_price: 1,   rating: 82 },
  { name: "Venkatesh Iyer",     role: "AR",   base_price: 1,   rating: 81 },
  { name: "Vijay Shankar",      role: "AR",   base_price: 0.5, rating: 75 },
  { name: "Deepak Hooda",       role: "AR",   base_price: 0.5, rating: 76 },
  { name: "Ramandeep Singh",    role: "AR",   base_price: 0.5, rating: 76 },
  { name: "Abhishek Porel",     role: "AR",   base_price: 0.5, rating: 74 },

  // ─── All-rounders (Overseas) ──────────────────────────
  { name: "Glenn Maxwell",      role: "AR",   base_price: 1.5, rating: 87, nationality: "AUS" },
  { name: "Andre Russell",      role: "AR",   base_price: 2,   rating: 90, nationality: "WI"  },
  { name: "Sunil Narine",       role: "AR",   base_price: 1.5, rating: 88, nationality: "WI"  },
  { name: "Cameron Green",      role: "AR",   base_price: 1.5, rating: 85, nationality: "AUS" },
  { name: "Mitchell Marsh",     role: "AR",   base_price: 1.5, rating: 86, nationality: "AUS" },
  { name: "Marcus Stoinis",     role: "AR",   base_price: 1.5, rating: 84, nationality: "AUS" },
  { name: "Moeen Ali",          role: "AR",   base_price: 1,   rating: 82, nationality: "ENG" },
  { name: "Sam Curran",         role: "AR",   base_price: 1.5, rating: 85, nationality: "ENG" },
  { name: "Liam Livingstone",   role: "AR",   base_price: 1.5, rating: 84, nationality: "ENG" },
  { name: "Marco Jansen",       role: "AR",   base_price: 1,   rating: 83, nationality: "RSA" },
  { name: "Tristan Stubbs",     role: "AR",   base_price: 1,   rating: 81, nationality: "RSA" },
  { name: "Wanindu Hasaranga",  role: "AR",   base_price: 1.5, rating: 86, nationality: "SL"  },
  { name: "Dunith Wellalage",   role: "AR",   base_price: 0.5, rating: 76, nationality: "SL"  },

  // ─── Bowlers (Indian — pace) ──────────────────────────
  { name: "Jasprit Bumrah",     role: "BOWL", base_price: 2,   rating: 96 },
  { name: "Mohammed Shami",     role: "BOWL", base_price: 1.5, rating: 88 },
  { name: "Mohammed Siraj",     role: "BOWL", base_price: 1.5, rating: 87 },
  { name: "Arshdeep Singh",     role: "BOWL", base_price: 1.5, rating: 86 },
  { name: "Deepak Chahar",      role: "BOWL", base_price: 1,   rating: 82 },
  { name: "Avesh Khan",         role: "BOWL", base_price: 1,   rating: 81 },
  { name: "Harshal Patel",      role: "BOWL", base_price: 1,   rating: 82 },
  { name: "T Natarajan",        role: "BOWL", base_price: 1,   rating: 81 },
  { name: "Mukesh Kumar",       role: "BOWL", base_price: 0.75,rating: 79 },
  { name: "Khaleel Ahmed",      role: "BOWL", base_price: 0.75,rating: 78 },
  { name: "Akash Madhwal",      role: "BOWL", base_price: 0.5, rating: 76 },
  { name: "Mukesh Choudhary",   role: "BOWL", base_price: 0.5, rating: 75 },
  { name: "Mayank Yadav",       role: "BOWL", base_price: 1,   rating: 83 },
  { name: "Umran Malik",        role: "BOWL", base_price: 0.75,rating: 80 },
  { name: "Prasidh Krishna",    role: "BOWL", base_price: 1,   rating: 81 },

  // ─── Bowlers (Indian — spin) ──────────────────────────
  { name: "Yuzvendra Chahal",   role: "BOWL", base_price: 1.5, rating: 86 },
  { name: "Kuldeep Yadav",      role: "BOWL", base_price: 1.5, rating: 86 },
  { name: "Ravi Bishnoi",       role: "BOWL", base_price: 1,   rating: 82 },
  { name: "Rahul Chahar",       role: "BOWL", base_price: 0.75,rating: 78 },
  { name: "Varun Chakaravarthy",role: "BOWL", base_price: 1,   rating: 84 },
  { name: "Piyush Chawla",      role: "BOWL", base_price: 0.5, rating: 75 },
  { name: "R Ashwin",           role: "BOWL", base_price: 1,   rating: 83 },
  { name: "Mayank Markande",    role: "BOWL", base_price: 0.5, rating: 75 },

  // ─── Bowlers (Overseas) ───────────────────────────────
  { name: "Trent Boult",        role: "BOWL", base_price: 1.5, rating: 88, nationality: "NZ"  },
  { name: "Mitchell Starc",     role: "BOWL", base_price: 2,   rating: 90, nationality: "AUS" },
  { name: "Pat Cummins",        role: "BOWL", base_price: 2,   rating: 91, nationality: "AUS" },
  { name: "Josh Hazlewood",     role: "BOWL", base_price: 1.5, rating: 87, nationality: "AUS" },
  { name: "Kagiso Rabada",      role: "BOWL", base_price: 2,   rating: 90, nationality: "RSA" },
  { name: "Anrich Nortje",      role: "BOWL", base_price: 1.5, rating: 86, nationality: "RSA" },
  { name: "Lockie Ferguson",    role: "BOWL", base_price: 1,   rating: 83, nationality: "NZ"  },
  { name: "Jofra Archer",       role: "BOWL", base_price: 1.5, rating: 87, nationality: "ENG" },
  { name: "Reece Topley",       role: "BOWL", base_price: 1,   rating: 82, nationality: "ENG" },
  { name: "Matheesha Pathirana",role: "BOWL", base_price: 1,   rating: 83, nationality: "SL"  },
  { name: "Maheesh Theekshana", role: "BOWL", base_price: 1,   rating: 82, nationality: "SL"  },
  { name: "Adam Zampa",         role: "BOWL", base_price: 1,   rating: 83, nationality: "AUS" },
  { name: "Rashid Khan",        role: "BOWL", base_price: 2,   rating: 92, nationality: "AFG" },
  { name: "Noor Ahmad",         role: "BOWL", base_price: 1,   rating: 82, nationality: "AFG" },
  { name: "Naveen-ul-Haq",      role: "BOWL", base_price: 1,   rating: 81, nationality: "AFG" },
  { name: "Gerald Coetzee",     role: "BOWL", base_price: 1,   rating: 80, nationality: "RSA" },

  // ─── Uncapped / depth ─────────────────────────────────
  { name: "Aniket Verma",       role: "BAT",  base_price: 0.3, rating: 72 },
  { name: "Vipraj Nigam",       role: "AR",   base_price: 0.3, rating: 71 },
  { name: "Karun Nair",         role: "BAT",  base_price: 0.5, rating: 76 },
  { name: "Manish Pandey",      role: "BAT",  base_price: 0.5, rating: 75 },
  { name: "Tushar Deshpande",   role: "BOWL", base_price: 0.5, rating: 75 },
  { name: "Nehal Wadhera",      role: "BAT",  base_price: 0.5, rating: 75 },
  { name: "Sameer Rizvi",       role: "BAT",  base_price: 0.3, rating: 72 },
  { name: "Atharva Taide",      role: "BAT",  base_price: 0.3, rating: 71 },
  { name: "Naman Dhir",         role: "BAT",  base_price: 0.3, rating: 71 },
  { name: "Anuj Rawat",         role: "WK",   base_price: 0.3, rating: 72 },
  { name: "Vishnu Vinod",       role: "WK",   base_price: 0.3, rating: 71 },
  { name: "Yash Dayal",         role: "BOWL", base_price: 0.5, rating: 76 },
  { name: "Naveen Saini",       role: "BOWL", base_price: 0.3, rating: 70 },
  { name: "Akash Deep",         role: "BOWL", base_price: 0.5, rating: 77 },
  { name: "Shardul Thakur",     role: "AR",   base_price: 0.75,rating: 78 },
  { name: "Harshit Rana",       role: "BOWL", base_price: 0.5, rating: 78 },
  { name: "Vaibhav Arora",      role: "BOWL", base_price: 0.5, rating: 76 },
  { name: "Kamran Ghulam",      role: "BAT",  base_price: 0.3, rating: 70 },
  { name: "Tim David",          role: "AR",   base_price: 1.5, rating: 84, nationality: "AUS" },
  { name: "Romario Shepherd",   role: "AR",   base_price: 1,   rating: 80, nationality: "WI"  },
  { name: "Nicholas Pooran",    role: "WK",   base_price: 2,   rating: 89, nationality: "WI"  },
  { name: "Andre Siddarth",     role: "BAT",  base_price: 0.3, rating: 70 },
  { name: "Vyshak Vijaykumar",  role: "BOWL", base_price: 0.3, rating: 72 },
  { name: "Shahbaz Ahmed",      role: "AR",   base_price: 0.5, rating: 75 },
  { name: "Tilak Verma Jr",     role: "BAT",  base_price: 0.3, rating: 70 },
  { name: "Suyash Sharma",      role: "BOWL", base_price: 0.5, rating: 76 },
  { name: "Kumar Kushagra",     role: "WK",   base_price: 0.3, rating: 72 },
  { name: "Donovan Ferreira",   role: "AR",   base_price: 0.5, rating: 76, nationality: "RSA" },
  { name: "Spencer Johnson",    role: "BOWL", base_price: 1,   rating: 81, nationality: "AUS" },
  { name: "Daryl Mitchell",     role: "AR",   base_price: 1,   rating: 83, nationality: "NZ"  },
  { name: "Rachin Ravindra",    role: "AR",   base_price: 1.5, rating: 85, nationality: "NZ"  },
  { name: "Tom Banton",         role: "BAT",  base_price: 0.5, rating: 77, nationality: "ENG" },
  { name: "Jamie Overton",      role: "AR",   base_price: 0.75,rating: 79, nationality: "ENG" },
  { name: "Corbin Bosch",       role: "AR",   base_price: 0.75,rating: 79, nationality: "RSA" },
  { name: "Jacob Bethell",      role: "AR",   base_price: 0.75,rating: 79, nationality: "ENG" },
  { name: "Ryan Rickelton",     role: "WK",   base_price: 0.75,rating: 80, nationality: "RSA" },
  { name: "Matthew Breetzke",   role: "BAT",  base_price: 0.5, rating: 77, nationality: "RSA" },

  // ─── EXPANDED POOL — 670 additional real cricketers (auto-generated) ──
  { name: "Sarfaraz Khan", role: "BAT", base_price: 0.5, rating: 78 },
  { name: "Hanuma Vihari", role: "BAT", base_price: 0.3, rating: 72 },
  { name: "Cheteshwar Pujara", role: "BAT", base_price: 0.5, rating: 76 },
  { name: "Ajinkya Rahane", role: "BAT", base_price: 0.3, rating: 74 },
  { name: "Murali Vijay", role: "BAT", base_price: 0.75, rating: 80 },
  { name: "Robin Uthappa", role: "BAT", base_price: 0.5, rating: 78 },
  { name: "Manoj Tiwary", role: "BAT", base_price: 0.75, rating: 82 },
  { name: "Suresh Raina", role: "BAT", base_price: 0.3, rating: 72 },
  { name: "Gautam Gambhir", role: "BAT", base_price: 0.5, rating: 76 },
  { name: "Parthiv Patel", role: "BAT", base_price: 0.3, rating: 72 },
  { name: "Mohammad Kaif", role: "BAT", base_price: 0.3, rating: 74 },
  { name: "Rohan Kunnummal", role: "BAT", base_price: 0.5, rating: 78 },
  { name: "Abhimanyu Easwaran", role: "BAT", base_price: 0.3, rating: 72 },
  { name: "Ricky Bhui", role: "BAT", base_price: 0.3, rating: 74 },
  { name: "Priyam Garg", role: "BAT", base_price: 0.5, rating: 78 },
  { name: "Yash Dhull", role: "BAT", base_price: 0.5, rating: 78 },
  { name: "Tanmay Agarwal", role: "BAT", base_price: 0.3, rating: 74 },
  { name: "Ravikumar Samarth", role: "BAT", base_price: 0.5, rating: 78 },
  { name: "Shubham Khajuria", role: "BAT", base_price: 0.75, rating: 80 },
  { name: "Ankit Kalsi", role: "BAT", base_price: 0.3, rating: 72 },
  { name: "Madhav Kaushik", role: "BAT", base_price: 0.75, rating: 80 },
  { name: "Aryaman Birla", role: "BAT", base_price: 0.5, rating: 78 },
  { name: "Vivrant Sharma", role: "BAT", base_price: 0.5, rating: 76 },
  { name: "Rajvardhan Hangargekar", role: "BAT", base_price: 0.3, rating: 74 },
  { name: "Avi Barot", role: "BAT", base_price: 0.75, rating: 82 },
  { name: "Hrithik Shokeen", role: "BAT", base_price: 0.5, rating: 76 },
  { name: "Sai Kishore", role: "BAT", base_price: 0.3, rating: 72 },
  { name: "Yash Thakur", role: "BAT", base_price: 0.3, rating: 74 },
  { name: "Aakash Singh", role: "BAT", base_price: 0.75, rating: 80 },
  { name: "Kumar Kartikeya", role: "BAT", base_price: 0.5, rating: 78 },
  { name: "Rishi Dhawan", role: "BAT", base_price: 0.75, rating: 80 },
  { name: "Shivam Mavi", role: "BAT", base_price: 0.75, rating: 80 },
  { name: "Khaleel Ansari", role: "BAT", base_price: 0.5, rating: 78 },
  { name: "Rajat Bhatia", role: "BAT", base_price: 1.0, rating: 84 },
  { name: "Manan Vohra", role: "BAT", base_price: 0.5, rating: 76 },
  { name: "Unmukt Chand", role: "BAT", base_price: 0.5, rating: 78 },
  { name: "KS Bharat", role: "BAT", base_price: 0.75, rating: 80 },
  { name: "Anuj Rawat", role: "BAT", base_price: 0.5, rating: 78 },
  { name: "Vishnu Solanki", role: "BAT", base_price: 0.75, rating: 80 },
  { name: "Salil Arora", role: "BAT", base_price: 0.5, rating: 78 },
  { name: "Tilak Verma", role: "BAT", base_price: 0.5, rating: 78 },
  { name: "Karthik Tyagi", role: "BAT", base_price: 0.3, rating: 72 },
  { name: "Aryan Juyal", role: "BAT", base_price: 0.3, rating: 74 },
  { name: "Aditya Tare", role: "BAT", base_price: 0.5, rating: 76 },
  { name: "Sridharan Sriram", role: "BAT", base_price: 0.3, rating: 72 },
  { name: "Naman Ojha", role: "BAT", base_price: 0.3, rating: 74 },
  { name: "Ankit Bawne", role: "BAT", base_price: 0.3, rating: 74 },
  { name: "Faiz Fazal", role: "BAT", base_price: 0.5, rating: 76 },
  { name: "Prashant Chopra", role: "BAT", base_price: 0.5, rating: 78 },
  { name: "Dhruv Shorey", role: "BAT", base_price: 0.5, rating: 76 },
  { name: "Jiwanjot Singh", role: "BAT", base_price: 0.5, rating: 76 },
  { name: "Shreyas Gopal", role: "BAT", base_price: 0.3, rating: 74 },
  { name: "Manpreet Gony", role: "BAT", base_price: 0.5, rating: 76 },
  { name: "Mandeep Singh", role: "BAT", base_price: 0.75, rating: 82 },
  { name: "Sandeep Sharma", role: "BAT", base_price: 0.5, rating: 78 },
  { name: "Iqbal Abdulla", role: "BAT", base_price: 0.5, rating: 78 },
  { name: "Rahul Tewatia", role: "BAT", base_price: 0.3, rating: 74 },
  { name: "Karn Sharma", role: "BAT", base_price: 0.75, rating: 80 },
  { name: "Pawan Negi", role: "BAT", base_price: 0.3, rating: 74 },
  { name: "Jaydev Unadkat", role: "BAT", base_price: 0.5, rating: 76 },
  { name: "Pradeep Sangwan", role: "BAT", base_price: 1.0, rating: 84 },
  { name: "Pankaj Singh", role: "BAT", base_price: 0.5, rating: 78 },
  { name: "Shams Mulani", role: "BAT", base_price: 0.5, rating: 78 },
  { name: "Sarfaraz Patel", role: "BAT", base_price: 0.5, rating: 78 },
  { name: "Shams Tabrez", role: "BAT", base_price: 0.75, rating: 80 },
  { name: "Aman Hakim Khan", role: "BAT", base_price: 0.75, rating: 80 },
  { name: "Tanay Thyagarajann", role: "BAT", base_price: 0.3, rating: 74 },
  { name: "Rinku Yadav", role: "BAT", base_price: 0.3, rating: 72 },
  { name: "Umesh Yadav", role: "BOWL", base_price: 0.3, rating: 74 },
  { name: "Ishant Sharma", role: "BOWL", base_price: 0.3, rating: 74 },
  { name: "Bhuvneshwar Kumar", role: "BOWL", base_price: 0.3, rating: 74 },
  { name: "Ashish Nehra", role: "BOWL", base_price: 0.75, rating: 82 },
  { name: "RP Singh", role: "BOWL", base_price: 0.75, rating: 80 },
  { name: "Munaf Patel", role: "BOWL", base_price: 0.3, rating: 74 },
  { name: "Irfan Pathan", role: "BOWL", base_price: 0.5, rating: 78 },
  { name: "Abhishek Nayar", role: "BOWL", base_price: 0.5, rating: 76 },
  { name: "Mohit Sharma", role: "BOWL", base_price: 0.75, rating: 82 },
  { name: "Siddarth Kaul", role: "BOWL", base_price: 0.5, rating: 76 },
  { name: "Nathu Singh", role: "BOWL", base_price: 0.3, rating: 74 },
  { name: "Anukul Roy", role: "BOWL", base_price: 0.5, rating: 78 },
  { name: "Ankit Rajpoot", role: "BOWL", base_price: 0.3, rating: 74 },
  { name: "Basil Thampi", role: "BOWL", base_price: 0.5, rating: 78 },
  { name: "Gurkeerat Mann", role: "BOWL", base_price: 0.75, rating: 82 },
  { name: "Lukman Meriwala", role: "BOWL", base_price: 0.5, rating: 76 },
  { name: "Aniket Choudhary", role: "BOWL", base_price: 0.3, rating: 74 },
  { name: "Mukesh Choudhary", role: "BOWL", base_price: 1.0, rating: 84 },
  { name: "Akash Singh", role: "BOWL", base_price: 0.5, rating: 76 },
  { name: "Chetan Sakariya", role: "BOWL", base_price: 0.3, rating: 72 },
  { name: "Ishan Porel", role: "BOWL", base_price: 0.3, rating: 70 },
  { name: "Atit Sheth", role: "BOWL", base_price: 0.3, rating: 72 },
  { name: "Yash Dayal", role: "BOWL", base_price: 0.5, rating: 78 },
  { name: "Kartik Tyagi", role: "BOWL", base_price: 0.75, rating: 80 },
  { name: "Rasikh Salam", role: "BOWL", base_price: 0.5, rating: 76 },
  { name: "Jaskaran Singh", role: "BOWL", base_price: 0.3, rating: 72 },
  { name: "Vidwath Kaverappa", role: "BOWL", base_price: 0.5, rating: 76 },
  { name: "Tushar Deshpande", role: "BOWL", base_price: 1.0, rating: 84 },
  { name: "Pavan Deshpande", role: "BOWL", base_price: 0.5, rating: 76 },
  { name: "Vyshak Vijaykumar", role: "BOWL", base_price: 0.75, rating: 82 },
  { name: "Yudhvir Singh Charak", role: "BOWL", base_price: 0.75, rating: 80 },
  { name: "Naveen Kumar", role: "BOWL", base_price: 0.3, rating: 70 },
  { name: "Aman Khan", role: "BOWL", base_price: 0.5, rating: 78 },
  { name: "Divesh Sharma", role: "BOWL", base_price: 0.5, rating: 78 },
  { name: "Saransh Jain", role: "BOWL", base_price: 0.5, rating: 76 },
  { name: "Shivam Sharma", role: "BOWL", base_price: 0.3, rating: 74 },
  { name: "Rajan Kumar", role: "BOWL", base_price: 0.5, rating: 78 },
  { name: "Ravi Kiran", role: "BOWL", base_price: 0.3, rating: 72 },
  { name: "Harbhajan Singh", role: "BOWL", base_price: 0.5, rating: 76 },
  { name: "Pragyan Ojha", role: "BOWL", base_price: 0.5, rating: 76 },
  { name: "Amit Mishra", role: "BOWL", base_price: 1.0, rating: 84 },
  { name: "Pravin Tambe", role: "BOWL", base_price: 0.75, rating: 82 },
  { name: "Jalaj Saxena", role: "BOWL", base_price: 0.3, rating: 74 },
  { name: "Mayank Markande", role: "BOWL", base_price: 0.5, rating: 78 },
  { name: "Yagnik Pathak", role: "BOWL", base_price: 0.3, rating: 74 },
  { name: "Saurabh Kumar", role: "BOWL", base_price: 0.75, rating: 82 },
  { name: "Manimaran Siddharth", role: "BOWL", base_price: 0.5, rating: 76 },
  { name: "Ravisrinivasan Sai Kishore", role: "BOWL", base_price: 0.5, rating: 78 },
  { name: "Akeal Hosein", role: "BOWL", base_price: 0.5, rating: 78 },
  { name: "Murugan Ashwin", role: "BOWL", base_price: 0.3, rating: 74 },
  { name: "Rishabh Tewatia", role: "BOWL", base_price: 0.75, rating: 80 },
  { name: "Aniket Verma", role: "BOWL", base_price: 0.5, rating: 78 },
  { name: "Parvez Rasool", role: "BOWL", base_price: 0.75, rating: 80 },
  { name: "Jagadeesha Suchith", role: "BOWL", base_price: 0.5, rating: 78 },
  { name: "Sumit Kumar", role: "BOWL", base_price: 0.5, rating: 76 },
  { name: "Krishnappa Gowtham", role: "BOWL", base_price: 0.3, rating: 70 },
  { name: "Karn Veer Kaushal", role: "BOWL", base_price: 0.75, rating: 82 },
  { name: "Nikhil Naik", role: "BOWL", base_price: 0.75, rating: 82 },
  { name: "Jayant Yadav", role: "BOWL", base_price: 0.75, rating: 80 },
  { name: "Saqib Mahmood", role: "BOWL", base_price: 0.5, rating: 76 },
  { name: "Yusuf Pathan", role: "AR", base_price: 0.75, rating: 80 },
  { name: "Stuart Binny", role: "AR", base_price: 0.75, rating: 82 },
  { name: "Bipul Sharma", role: "AR", base_price: 0.3, rating: 70 },
  { name: "Pradeep Sahu", role: "AR", base_price: 0.5, rating: 76 },
  { name: "Ankit Sharma", role: "AR", base_price: 0.3, rating: 70 },
  { name: "Akshay Karnewar", role: "AR", base_price: 0.5, rating: 78 },
  { name: "Pankaj Jaswal", role: "AR", base_price: 0.5, rating: 78 },
  { name: "Riley Meredith", role: "AR", base_price: 0.3, rating: 72 },
  { name: "Ankit Soni", role: "AR", base_price: 0.5, rating: 76 },
  { name: "Shahbaz Nadeem", role: "AR", base_price: 0.3, rating: 74 },
  { name: "Pulkit Narang", role: "AR", base_price: 0.75, rating: 80 },
  { name: "Karanveer Singh", role: "AR", base_price: 0.3, rating: 74 },
  { name: "Manoj Bhandage", role: "AR", base_price: 0.3, rating: 72 },
  { name: "Nishant Sindhu", role: "AR", base_price: 0.75, rating: 82 },
  { name: "Krish Bhagat", role: "AR", base_price: 0.5, rating: 76 },
  { name: "Prerak Mankad", role: "AR", base_price: 0.3, rating: 74 },
  { name: "Manvanth Kumar L", role: "AR", base_price: 0.5, rating: 76 },
  { name: "Rahul Tripathi", role: "AR", base_price: 0.3, rating: 72 },
  { name: "Kuldeep Sen", role: "AR", base_price: 0.3, rating: 72 },
  { name: "Vishnu Vinod", role: "AR", base_price: 0.3, rating: 74 },
  { name: "Suyash Sharma", role: "AR", base_price: 0.5, rating: 76 },
  { name: "Yashpal Singh", role: "AR", base_price: 0.3, rating: 72 },
  { name: "Ravi Bishnoi", role: "AR", base_price: 0.3, rating: 70 },
  { name: "Wriddhiman Saha", role: "WK", base_price: 0.5, rating: 76 },
  { name: "Prashant Solanki", role: "WK", base_price: 0.3, rating: 72 },
  { name: "Kumar Kushagra", role: "WK", base_price: 0.3, rating: 72 },
  { name: "Upendra Yadav", role: "WK", base_price: 0.75, rating: 80 },
  { name: "Bharat Chipli", role: "WK", base_price: 0.5, rating: 76 },
  { name: "Rakesh Patel", role: "WK", base_price: 0.5, rating: 78 },
  { name: "Aryan Roy", role: "WK", base_price: 0.5, rating: 78 },
  { name: "Smit Patel", role: "WK", base_price: 0.3, rating: 74 },
  { name: "Akshat Rashtrapal", role: "WK", base_price: 0.3, rating: 74 },
  { name: "Robin Bist", role: "WK", base_price: 0.3, rating: 74 },
  { name: "Rishabh Pant Jr", role: "WK", base_price: 0.5, rating: 78 },
  { name: "Saurabh Tiwary", role: "WK", base_price: 0.5, rating: 76 },
  { name: "Vishal Jaiswal", role: "WK", base_price: 0.75, rating: 82 },
  { name: "Mahek Bhandari", role: "WK", base_price: 0.3, rating: 74 },
  { name: "David Warner", role: "BAT", base_price: 0.75, rating: 80, nationality: "AUS" },
  { name: "Steve Smith", role: "BAT", base_price: 1.5, rating: 86, nationality: "AUS" },
  { name: "Aaron Finch", role: "BAT", base_price: 0.75, rating: 78, nationality: "AUS" },
  { name: "Marcus Harris", role: "BAT", base_price: 0.75, rating: 78, nationality: "AUS" },
  { name: "Matt Renshaw", role: "BAT", base_price: 0.75, rating: 80, nationality: "AUS" },
  { name: "Peter Handscomb", role: "BAT", base_price: 0.75, rating: 80, nationality: "AUS" },
  { name: "Marnus Labuschagne", role: "BAT", base_price: 0.75, rating: 78, nationality: "AUS" },
  { name: "Beau Webster", role: "BAT", base_price: 0.75, rating: 78, nationality: "AUS" },
  { name: "Jake Fraser-McGurk", role: "BAT", base_price: 1.5, rating: 86, nationality: "AUS" },
  { name: "Matthew Short", role: "BAT", base_price: 0.75, rating: 80, nationality: "AUS" },
  { name: "Josh Inglis", role: "BAT", base_price: 1.5, rating: 86, nationality: "AUS" },
  { name: "Joe Burns", role: "BAT", base_price: 1.0, rating: 82, nationality: "AUS" },
  { name: "Usman Khawaja", role: "BAT", base_price: 0.5, rating: 76, nationality: "AUS" },
  { name: "Marcus Stoinis", role: "BAT", base_price: 2.0, rating: 90, nationality: "AUS" },
  { name: "Chris Lynn", role: "BAT", base_price: 1.5, rating: 86, nationality: "AUS" },
  { name: "D'Arcy Short", role: "BAT", base_price: 1.5, rating: 88, nationality: "AUS" },
  { name: "Nathan Lyon", role: "BOWL", base_price: 1.5, rating: 86, nationality: "AUS" },
  { name: "Sean Abbott", role: "BOWL", base_price: 1.5, rating: 86, nationality: "AUS" },
  { name: "Jhye Richardson", role: "BOWL", base_price: 0.75, rating: 78, nationality: "AUS" },
  { name: "Andrew Tye", role: "BOWL", base_price: 0.75, rating: 80, nationality: "AUS" },
  { name: "Wes Agar", role: "BOWL", base_price: 0.75, rating: 80, nationality: "AUS" },
  { name: "Nathan Ellis", role: "BOWL", base_price: 0.5, rating: 76, nationality: "AUS" },
  { name: "Xavier Bartlett", role: "BOWL", base_price: 0.75, rating: 80, nationality: "AUS" },
  { name: "Lance Morris", role: "BOWL", base_price: 2.0, rating: 90, nationality: "AUS" },
  { name: "Mark Steketee", role: "BOWL", base_price: 0.75, rating: 78, nationality: "AUS" },
  { name: "Daniel Sams", role: "BOWL", base_price: 1.0, rating: 84, nationality: "AUS" },
  { name: "Ben Dwarshuis", role: "BOWL", base_price: 0.75, rating: 80, nationality: "AUS" },
  { name: "Tanveer Sangha", role: "BOWL", base_price: 0.75, rating: 80, nationality: "AUS" },
  { name: "Tim Murphy", role: "BOWL", base_price: 1.5, rating: 88, nationality: "AUS" },
  { name: "Jason Behrendorff", role: "BOWL", base_price: 2.0, rating: 90, nationality: "AUS" },
  { name: "Aaron Hardie", role: "AR", base_price: 1.0, rating: 82, nationality: "AUS" },
  { name: "Cooper Connolly", role: "AR", base_price: 1.0, rating: 84, nationality: "AUS" },
  { name: "Tim David", role: "AR", base_price: 0.75, rating: 78, nationality: "AUS" },
  { name: "Mitchell Owen", role: "AR", base_price: 0.75, rating: 80, nationality: "AUS" },
  { name: "Will Sutherland", role: "AR", base_price: 1.5, rating: 88, nationality: "AUS" },
  { name: "Henry Hunt", role: "AR", base_price: 1.0, rating: 82, nationality: "AUS" },
  { name: "Mackenzie Harvey", role: "AR", base_price: 1.0, rating: 82, nationality: "AUS" },
  { name: "Nick Hobson", role: "AR", base_price: 1.0, rating: 84, nationality: "AUS" },
  { name: "Alex Carey", role: "WK", base_price: 0.5, rating: 76, nationality: "AUS" },
  { name: "Tim Paine", role: "WK", base_price: 1.0, rating: 82, nationality: "AUS" },
  { name: "Sam Heazlett", role: "WK", base_price: 1.0, rating: 82, nationality: "AUS" },
  { name: "Josh Philippe", role: "WK", base_price: 1.5, rating: 86, nationality: "AUS" },
  { name: "Ben McDermott", role: "WK", base_price: 0.75, rating: 78, nationality: "AUS" },
  { name: "Matthew Wade", role: "WK", base_price: 1.5, rating: 88, nationality: "AUS" },
  { name: "Peter Nevill", role: "WK", base_price: 0.5, rating: 76, nationality: "AUS" },
  { name: "Joe Root", role: "BAT", base_price: 0.75, rating: 78, nationality: "ENG" },
  { name: "Ben Duckett", role: "BAT", base_price: 1.0, rating: 82, nationality: "ENG" },
  { name: "Harry Brook", role: "BAT", base_price: 1.0, rating: 82, nationality: "ENG" },
  { name: "Ollie Pope", role: "BAT", base_price: 0.75, rating: 78, nationality: "ENG" },
  { name: "Zak Crawley", role: "BAT", base_price: 0.5, rating: 76, nationality: "ENG" },
  { name: "James Vince", role: "BAT", base_price: 1.5, rating: 86, nationality: "ENG" },
  { name: "Alex Hales", role: "BAT", base_price: 0.75, rating: 78, nationality: "ENG" },
  { name: "Jason Roy", role: "BAT", base_price: 1.0, rating: 82, nationality: "ENG" },
  { name: "Dawid Malan", role: "BAT", base_price: 1.0, rating: 82, nationality: "ENG" },
  { name: "Will Smeed", role: "BAT", base_price: 0.75, rating: 80, nationality: "ENG" },
  { name: "Tom Kohler-Cadmore", role: "BAT", base_price: 1.0, rating: 82, nationality: "ENG" },
  { name: "Tom Abell", role: "BAT", base_price: 1.0, rating: 82, nationality: "ENG" },
  { name: "Joe Clarke", role: "BAT", base_price: 1.5, rating: 88, nationality: "ENG" },
  { name: "Eddie Byrom", role: "BAT", base_price: 0.75, rating: 78, nationality: "ENG" },
  { name: "Sam Hain", role: "BAT", base_price: 1.0, rating: 84, nationality: "ENG" },
  { name: "James Anderson", role: "BOWL", base_price: 0.75, rating: 78, nationality: "ENG" },
  { name: "Stuart Broad", role: "BOWL", base_price: 0.75, rating: 80, nationality: "ENG" },
  { name: "Mark Wood", role: "BOWL", base_price: 1.0, rating: 82, nationality: "ENG" },
  { name: "Chris Woakes", role: "BOWL", base_price: 0.75, rating: 80, nationality: "ENG" },
  { name: "Olly Stone", role: "BOWL", base_price: 0.75, rating: 80, nationality: "ENG" },
  { name: "Brydon Carse", role: "BOWL", base_price: 0.5, rating: 76, nationality: "ENG" },
  { name: "Matthew Potts", role: "BOWL", base_price: 0.75, rating: 80, nationality: "ENG" },
  { name: "Josh Tongue", role: "BOWL", base_price: 2.0, rating: 90, nationality: "ENG" },
  { name: "Tymal Mills", role: "BOWL", base_price: 2.0, rating: 90, nationality: "ENG" },
  { name: "Luke Wood", role: "BOWL", base_price: 0.5, rating: 76, nationality: "ENG" },
  { name: "David Willey", role: "BOWL", base_price: 0.75, rating: 78, nationality: "ENG" },
  { name: "Reece Topley", role: "BOWL", base_price: 0.75, rating: 78, nationality: "ENG" },
  { name: "Adil Rashid", role: "BOWL", base_price: 1.5, rating: 88, nationality: "ENG" },
  { name: "Rehan Ahmed", role: "BOWL", base_price: 1.5, rating: 86, nationality: "ENG" },
  { name: "Tom Hartley", role: "BOWL", base_price: 1.5, rating: 86, nationality: "ENG" },
  { name: "Shoaib Bashir", role: "BOWL", base_price: 0.75, rating: 80, nationality: "ENG" },
  { name: "Jack Leach", role: "BOWL", base_price: 0.75, rating: 78, nationality: "ENG" },
  { name: "Mason Crane", role: "BOWL", base_price: 1.5, rating: 86, nationality: "ENG" },
  { name: "Dom Bess", role: "BOWL", base_price: 1.0, rating: 84, nationality: "ENG" },
  { name: "Jake Lintott", role: "BOWL", base_price: 1.0, rating: 82, nationality: "ENG" },
  { name: "Calvin Harrison", role: "BOWL", base_price: 2.0, rating: 90, nationality: "ENG" },
  { name: "Chris Jordan", role: "AR", base_price: 1.0, rating: 82, nationality: "ENG" },
  { name: "Ben Stokes", role: "AR", base_price: 0.5, rating: 74, nationality: "ENG" },
  { name: "Jacob Bethell", role: "AR", base_price: 1.0, rating: 84, nationality: "ENG" },
  { name: "Rocky Flintoff", role: "AR", base_price: 0.75, rating: 80, nationality: "ENG" },
  { name: "Tom Lawes", role: "AR", base_price: 1.0, rating: 82, nationality: "ENG" },
  { name: "Will Jacks", role: "AR", base_price: 1.5, rating: 88, nationality: "ENG" },
  { name: "George Garton", role: "AR", base_price: 0.5, rating: 76, nationality: "ENG" },
  { name: "Lewis Goldsworthy", role: "AR", base_price: 0.5, rating: 76, nationality: "ENG" },
  { name: "Ben McKinney", role: "AR", base_price: 0.5, rating: 76, nationality: "ENG" },
  { name: "Ethan Brookes", role: "AR", base_price: 1.0, rating: 82, nationality: "ENG" },
  { name: "Jonny Bairstow", role: "WK", base_price: 0.75, rating: 78, nationality: "ENG" },
  { name: "Ben Foakes", role: "WK", base_price: 1.0, rating: 82, nationality: "ENG" },
  { name: "Jamie Smith", role: "WK", base_price: 1.0, rating: 84, nationality: "ENG" },
  { name: "Sam Billings", role: "WK", base_price: 0.75, rating: 78, nationality: "ENG" },
  { name: "John Simpson", role: "WK", base_price: 1.0, rating: 82, nationality: "ENG" },
  { name: "Ollie Robinson", role: "WK", base_price: 0.75, rating: 78, nationality: "ENG" },
  { name: "Chris Cooke", role: "WK", base_price: 1.0, rating: 82, nationality: "ENG" },
  { name: "Aiden Markram", role: "BAT", base_price: 1.5, rating: 86, nationality: "RSA" },
  { name: "Temba Bavuma", role: "BAT", base_price: 1.5, rating: 86, nationality: "RSA" },
  { name: "Rassie van der Dussen", role: "BAT", base_price: 0.5, rating: 76, nationality: "RSA" },
  { name: "David Miller", role: "BAT", base_price: 0.75, rating: 80, nationality: "RSA" },
  { name: "Reeza Hendricks", role: "BAT", base_price: 0.75, rating: 78, nationality: "RSA" },
  { name: "Tony de Zorzi", role: "BAT", base_price: 0.5, rating: 74, nationality: "RSA" },
  { name: "Dewald Brevis", role: "BAT", base_price: 1.0, rating: 84, nationality: "RSA" },
  { name: "Khaya Zondo", role: "BAT", base_price: 1.0, rating: 82, nationality: "RSA" },
  { name: "Janneman Malan", role: "BAT", base_price: 0.75, rating: 78, nationality: "RSA" },
  { name: "Ryan Rickelton", role: "BAT", base_price: 1.0, rating: 84, nationality: "RSA" },
  { name: "Pieter Malan", role: "BAT", base_price: 1.0, rating: 82, nationality: "RSA" },
  { name: "Jiveshen Pillay", role: "BAT", base_price: 0.75, rating: 80, nationality: "RSA" },
  { name: "Sinethemba Qeshile", role: "BAT", base_price: 0.5, rating: 74, nationality: "RSA" },
  { name: "Lungi Ngidi", role: "BOWL", base_price: 0.5, rating: 76, nationality: "RSA" },
  { name: "Nandre Burger", role: "BOWL", base_price: 1.5, rating: 86, nationality: "RSA" },
  { name: "Lutho Sipamla", role: "BOWL", base_price: 1.5, rating: 86, nationality: "RSA" },
  { name: "Junior Dala", role: "BOWL", base_price: 1.0, rating: 82, nationality: "RSA" },
  { name: "Beuran Hendricks", role: "BOWL", base_price: 1.5, rating: 86, nationality: "RSA" },
  { name: "Wiaan Mulder", role: "BOWL", base_price: 1.0, rating: 82, nationality: "RSA" },
  { name: "Bjorn Fortuin", role: "BOWL", base_price: 0.75, rating: 78, nationality: "RSA" },
  { name: "Tabraiz Shamsi", role: "BOWL", base_price: 0.5, rating: 76, nationality: "RSA" },
  { name: "Keshav Maharaj", role: "BOWL", base_price: 0.75, rating: 80, nationality: "RSA" },
  { name: "Imran Tahir", role: "BOWL", base_price: 1.5, rating: 86, nationality: "RSA" },
  { name: "George Linde", role: "BOWL", base_price: 1.0, rating: 84, nationality: "RSA" },
  { name: "Senuran Muthusamy", role: "BOWL", base_price: 1.5, rating: 86, nationality: "RSA" },
  { name: "Lizaad Williams", role: "BOWL", base_price: 1.5, rating: 86, nationality: "RSA" },
  { name: "Andile Phehlukwayo", role: "AR", base_price: 0.75, rating: 78, nationality: "RSA" },
  { name: "Dwaine Pretorius", role: "AR", base_price: 0.75, rating: 78, nationality: "RSA" },
  { name: "Wayne Parnell", role: "AR", base_price: 0.5, rating: 76, nationality: "RSA" },
  { name: "Sisanda Magala", role: "AR", base_price: 1.0, rating: 84, nationality: "RSA" },
  { name: "Mihlali Mpongwana", role: "AR", base_price: 1.5, rating: 86, nationality: "RSA" },
  { name: "Patrick Kruger", role: "AR", base_price: 0.75, rating: 80, nationality: "RSA" },
  { name: "Shaun von Berg", role: "AR", base_price: 1.0, rating: 82, nationality: "RSA" },
  { name: "Heinrich Klaasen", role: "WK", base_price: 0.75, rating: 78, nationality: "RSA" },
  { name: "Kyle Verreynne", role: "WK", base_price: 1.5, rating: 88, nationality: "RSA" },
  { name: "Clyde Fortuin", role: "WK", base_price: 2.0, rating: 90, nationality: "RSA" },
  { name: "Rudi Second", role: "WK", base_price: 1.0, rating: 84, nationality: "RSA" },
  { name: "Lhuan-dre Pretorius", role: "WK", base_price: 1.5, rating: 86, nationality: "RSA" },
  { name: "Tom Latham", role: "BAT", base_price: 0.5, rating: 74, nationality: "NZ" },
  { name: "Will Young", role: "BAT", base_price: 1.0, rating: 84, nationality: "NZ" },
  { name: "Henry Nicholls", role: "BAT", base_price: 0.75, rating: 80, nationality: "NZ" },
  { name: "Mark Chapman", role: "BAT", base_price: 1.5, rating: 88, nationality: "NZ" },
  { name: "Finn Allen", role: "BAT", base_price: 1.0, rating: 84, nationality: "NZ" },
  { name: "Tim Seifert", role: "BAT", base_price: 1.5, rating: 86, nationality: "NZ" },
  { name: "Glenn Phillips", role: "BAT", base_price: 1.0, rating: 84, nationality: "NZ" },
  { name: "Tom Blundell", role: "BAT", base_price: 0.75, rating: 78, nationality: "NZ" },
  { name: "Daryl Mitchell", role: "BAT", base_price: 1.0, rating: 84, nationality: "NZ" },
  { name: "Michael Bracewell", role: "BAT", base_price: 0.5, rating: 76, nationality: "NZ" },
  { name: "Dane Cleaver", role: "BAT", base_price: 1.5, rating: 86, nationality: "NZ" },
  { name: "Mitchell Hay", role: "BAT", base_price: 1.5, rating: 86, nationality: "NZ" },
  { name: "Tim Robinson", role: "BAT", base_price: 0.75, rating: 78, nationality: "NZ" },
  { name: "Cam Fletcher", role: "BAT", base_price: 1.0, rating: 84, nationality: "NZ" },
  { name: "Tim Southee", role: "BOWL", base_price: 0.75, rating: 80, nationality: "NZ" },
  { name: "Neil Wagner", role: "BOWL", base_price: 0.75, rating: 80, nationality: "NZ" },
  { name: "Matt Henry", role: "BOWL", base_price: 1.0, rating: 84, nationality: "NZ" },
  { name: "Kyle Jamieson", role: "BOWL", base_price: 0.75, rating: 78, nationality: "NZ" },
  { name: "Ish Sodhi", role: "BOWL", base_price: 0.5, rating: 74, nationality: "NZ" },
  { name: "Mitchell Santner", role: "BOWL", base_price: 0.75, rating: 78, nationality: "NZ" },
  { name: "Ajaz Patel", role: "BOWL", base_price: 0.75, rating: 80, nationality: "NZ" },
  { name: "Ben Sears", role: "BOWL", base_price: 1.5, rating: 86, nationality: "NZ" },
  { name: "Will O'Rourke", role: "BOWL", base_price: 1.5, rating: 88, nationality: "NZ" },
  { name: "Blair Tickner", role: "BOWL", base_price: 0.75, rating: 78, nationality: "NZ" },
  { name: "William ORourke", role: "BOWL", base_price: 1.0, rating: 82, nationality: "NZ" },
  { name: "Jacob Duffy", role: "BOWL", base_price: 0.75, rating: 80, nationality: "NZ" },
  { name: "Ben Lister", role: "BOWL", base_price: 2.0, rating: 90, nationality: "NZ" },
  { name: "Hamish Bennett", role: "BOWL", base_price: 1.0, rating: 82, nationality: "NZ" },
  { name: "James Neesham", role: "AR", base_price: 1.5, rating: 88, nationality: "NZ" },
  { name: "Colin de Grandhomme", role: "AR", base_price: 0.5, rating: 76, nationality: "NZ" },
  { name: "Doug Bracewell", role: "AR", base_price: 1.5, rating: 88, nationality: "NZ" },
  { name: "Henry Shipley", role: "AR", base_price: 0.75, rating: 78, nationality: "NZ" },
  { name: "Zak Foulkes", role: "AR", base_price: 1.5, rating: 88, nationality: "NZ" },
  { name: "Logan van Beek", role: "AR", base_price: 0.75, rating: 78, nationality: "NZ" },
  { name: "Cole McConchie", role: "AR", base_price: 0.5, rating: 76, nationality: "NZ" },
  { name: "BJ Watling", role: "WK", base_price: 0.75, rating: 80, nationality: "NZ" },
  { name: "Nick Kelly", role: "WK", base_price: 1.0, rating: 84, nationality: "NZ" },
  { name: "Frankie Mackay", role: "WK", base_price: 0.75, rating: 80, nationality: "NZ" },
  { name: "Bryan Charlton", role: "WK", base_price: 1.0, rating: 82, nationality: "NZ" },
  { name: "Brandon King", role: "BAT", base_price: 1.0, rating: 82, nationality: "WI" },
  { name: "Johnson Charles", role: "BAT", base_price: 0.75, rating: 80, nationality: "WI" },
  { name: "Evin Lewis", role: "BAT", base_price: 1.0, rating: 82, nationality: "WI" },
  { name: "Kyle Mayers", role: "BAT", base_price: 0.75, rating: 78, nationality: "WI" },
  { name: "Brandon McMullen", role: "BAT", base_price: 1.0, rating: 84, nationality: "WI" },
  { name: "Shai Hope", role: "BAT", base_price: 0.5, rating: 74, nationality: "WI" },
  { name: "Jermaine Blackwood", role: "BAT", base_price: 1.5, rating: 86, nationality: "WI" },
  { name: "Kjorn Ottley", role: "BAT", base_price: 1.0, rating: 82, nationality: "WI" },
  { name: "Tagenarine Chanderpaul", role: "BAT", base_price: 1.0, rating: 84, nationality: "WI" },
  { name: "Kavem Hodge", role: "BAT", base_price: 1.0, rating: 84, nationality: "WI" },
  { name: "Roston Chase", role: "BAT", base_price: 1.0, rating: 82, nationality: "WI" },
  { name: "Alick Athanaze", role: "BAT", base_price: 0.75, rating: 80, nationality: "WI" },
  { name: "Sherfane Rutherford", role: "BAT", base_price: 0.5, rating: 76, nationality: "WI" },
  { name: "Jason Holder", role: "BOWL", base_price: 1.0, rating: 82, nationality: "WI" },
  { name: "Alzarri Joseph", role: "BOWL", base_price: 0.75, rating: 80, nationality: "WI" },
  { name: "Shamar Joseph", role: "BOWL", base_price: 0.75, rating: 80, nationality: "WI" },
  { name: "Kemar Roach", role: "BOWL", base_price: 1.5, rating: 86, nationality: "WI" },
  { name: "Oshane Thomas", role: "BOWL", base_price: 1.0, rating: 84, nationality: "WI" },
  { name: "Gudakesh Motie", role: "BOWL", base_price: 0.75, rating: 80, nationality: "WI" },
  { name: "Kevin Sinclair", role: "BOWL", base_price: 0.75, rating: 80, nationality: "WI" },
  { name: "Yannic Cariah", role: "BOWL", base_price: 0.75, rating: 80, nationality: "WI" },
  { name: "Hayden Walsh", role: "BOWL", base_price: 0.75, rating: 80, nationality: "WI" },
  { name: "Obed McCoy", role: "BOWL", base_price: 0.5, rating: 76, nationality: "WI" },
  { name: "Jayden Seales", role: "BOWL", base_price: 0.75, rating: 80, nationality: "WI" },
  { name: "Anderson Phillip", role: "BOWL", base_price: 1.5, rating: 88, nationality: "WI" },
  { name: "Rovman Powell", role: "AR", base_price: 1.5, rating: 86, nationality: "WI" },
  { name: "Odean Smith", role: "AR", base_price: 1.0, rating: 82, nationality: "WI" },
  { name: "Keemo Paul", role: "AR", base_price: 0.75, rating: 80, nationality: "WI" },
  { name: "Jason Mohammed", role: "AR", base_price: 1.0, rating: 82, nationality: "WI" },
  { name: "Chemar Holder", role: "AR", base_price: 0.5, rating: 74, nationality: "WI" },
  { name: "Justin Greaves", role: "AR", base_price: 0.75, rating: 78, nationality: "WI" },
  { name: "Andrew McBrine", role: "AR", base_price: 0.75, rating: 80, nationality: "WI" },
  { name: "Joshua Da Silva", role: "WK", base_price: 1.0, rating: 82, nationality: "WI" },
  { name: "Tevin Imlach", role: "WK", base_price: 1.0, rating: 82, nationality: "WI" },
  { name: "Amir Jangoo", role: "WK", base_price: 0.75, rating: 80, nationality: "WI" },
  { name: "Mikyle Louis", role: "WK", base_price: 0.75, rating: 80, nationality: "WI" },
  { name: "Devon Thomas", role: "WK", base_price: 0.75, rating: 78, nationality: "WI" },
  { name: "Pathum Nissanka", role: "BAT", base_price: 0.75, rating: 80, nationality: "SL" },
  { name: "Kusal Mendis", role: "BAT", base_price: 1.5, rating: 86, nationality: "SL" },
  { name: "Charith Asalanka", role: "BAT", base_price: 1.0, rating: 84, nationality: "SL" },
  { name: "Dhananjaya de Silva", role: "BAT", base_price: 0.75, rating: 78, nationality: "SL" },
  { name: "Sadeera Samarawickrama", role: "BAT", base_price: 0.5, rating: 76, nationality: "SL" },
  { name: "Avishka Fernando", role: "BAT", base_price: 1.0, rating: 82, nationality: "SL" },
  { name: "Bhanuka Rajapaksa", role: "BAT", base_price: 1.0, rating: 82, nationality: "SL" },
  { name: "Dinesh Chandimal", role: "BAT", base_price: 0.75, rating: 80, nationality: "SL" },
  { name: "Angelo Mathews", role: "BAT", base_price: 1.0, rating: 84, nationality: "SL" },
  { name: "Niroshan Dickwella", role: "BAT", base_price: 1.0, rating: 84, nationality: "SL" },
  { name: "Lahiru Udara", role: "BAT", base_price: 1.0, rating: 82, nationality: "SL" },
  { name: "Pawan Rathnayake", role: "BAT", base_price: 0.75, rating: 78, nationality: "SL" },
  { name: "Lasith Embuldeniya", role: "BOWL", base_price: 0.75, rating: 78, nationality: "SL" },
  { name: "Asitha Fernando", role: "BOWL", base_price: 0.5, rating: 74, nationality: "SL" },
  { name: "Kasun Rajitha", role: "BOWL", base_price: 0.75, rating: 78, nationality: "SL" },
  { name: "Dilshan Madushanka", role: "BOWL", base_price: 0.75, rating: 80, nationality: "SL" },
  { name: "Vishwa Fernando", role: "BOWL", base_price: 1.5, rating: 86, nationality: "SL" },
  { name: "Nuwan Thushara", role: "BOWL", base_price: 0.5, rating: 76, nationality: "SL" },
  { name: "Binura Fernando", role: "BOWL", base_price: 0.75, rating: 80, nationality: "SL" },
  { name: "Dushmantha Chameera", role: "BOWL", base_price: 1.0, rating: 82, nationality: "SL" },
  { name: "Lakshitha Manasinghe", role: "BOWL", base_price: 0.75, rating: 78, nationality: "SL" },
  { name: "Akila Dananjaya", role: "BOWL", base_price: 1.0, rating: 84, nationality: "SL" },
  { name: "Praveen Jayawickrama", role: "BOWL", base_price: 1.0, rating: 82, nationality: "SL" },
  { name: "Jeffrey Vandersay", role: "BOWL", base_price: 0.75, rating: 78, nationality: "SL" },
  { name: "Ramesh Mendis", role: "BOWL", base_price: 1.0, rating: 82, nationality: "SL" },
  { name: "Lahiru Kumara", role: "BOWL", base_price: 0.5, rating: 74, nationality: "SL" },
  { name: "Pulina Tharanga", role: "BOWL", base_price: 1.0, rating: 84, nationality: "SL" },
  { name: "Chamika Karunaratne", role: "AR", base_price: 1.0, rating: 84, nationality: "SL" },
  { name: "Dasun Shanaka", role: "AR", base_price: 0.5, rating: 76, nationality: "SL" },
  { name: "Kamindu Mendis", role: "AR", base_price: 0.75, rating: 80, nationality: "SL" },
  { name: "Janith Liyanage", role: "AR", base_price: 0.75, rating: 78, nationality: "SL" },
  { name: "Wanindu Hasaranga", role: "AR", base_price: 1.5, rating: 88, nationality: "SL" },
  { name: "Dunith Wellalage", role: "AR", base_price: 1.0, rating: 82, nationality: "SL" },
  { name: "Shevon Daniel", role: "AR", base_price: 0.5, rating: 76, nationality: "SL" },
  { name: "Kusal Janith Perera", role: "WK", base_price: 0.75, rating: 78, nationality: "SL" },
  { name: "Sahan Arachchige", role: "WK", base_price: 1.5, rating: 86, nationality: "SL" },
  { name: "Rahmanullah Gurbaz", role: "BAT", base_price: 1.0, rating: 82, nationality: "AFG" },
  { name: "Ibrahim Zadran", role: "BAT", base_price: 2.0, rating: 90, nationality: "AFG" },
  { name: "Hazratullah Zazai", role: "BAT", base_price: 1.0, rating: 82, nationality: "AFG" },
  { name: "Sediqullah Atal", role: "BAT", base_price: 1.5, rating: 88, nationality: "AFG" },
  { name: "Karim Janat", role: "BAT", base_price: 1.5, rating: 86, nationality: "AFG" },
  { name: "Najibullah Zadran", role: "BAT", base_price: 1.0, rating: 82, nationality: "AFG" },
  { name: "Riaz Hassan", role: "BAT", base_price: 1.0, rating: 84, nationality: "AFG" },
  { name: "Darwish Rasooli", role: "BAT", base_price: 1.0, rating: 82, nationality: "AFG" },
  { name: "Hashmatullah Shahidi", role: "BAT", base_price: 1.5, rating: 86, nationality: "AFG" },
  { name: "Mujeeb Ur Rahman", role: "BOWL", base_price: 1.0, rating: 82, nationality: "AFG" },
  { name: "Fazalhaq Farooqi", role: "BOWL", base_price: 1.5, rating: 86, nationality: "AFG" },
  { name: "Naveen ul Haq", role: "BOWL", base_price: 1.0, rating: 84, nationality: "AFG" },
  { name: "Fareed Ahmad", role: "BOWL", base_price: 0.75, rating: 80, nationality: "AFG" },
  { name: "Wafadar Momand", role: "BOWL", base_price: 0.75, rating: 78, nationality: "AFG" },
  { name: "Salim Safi", role: "BOWL", base_price: 0.75, rating: 78, nationality: "AFG" },
  { name: "AM Ghazanfar", role: "BOWL", base_price: 1.0, rating: 82, nationality: "AFG" },
  { name: "Allah Mohammad Ghazanfar", role: "BOWL", base_price: 1.0, rating: 84, nationality: "AFG" },
  { name: "Sharafuddin Ashraf", role: "BOWL", base_price: 1.0, rating: 82, nationality: "AFG" },
  { name: "Zia ur Rehman", role: "BOWL", base_price: 1.0, rating: 82, nationality: "AFG" },
  { name: "Mohammad Nabi", role: "AR", base_price: 0.75, rating: 78, nationality: "AFG" },
  { name: "Azmatullah Omarzai", role: "AR", base_price: 0.5, rating: 76, nationality: "AFG" },
  { name: "Gulbadin Naib", role: "AR", base_price: 0.75, rating: 78, nationality: "AFG" },
  { name: "Qais Ahmad", role: "AR", base_price: 0.75, rating: 80, nationality: "AFG" },
  { name: "Nangialai Kharote", role: "AR", base_price: 1.0, rating: 82, nationality: "AFG" },
  { name: "Ikram Alikhil", role: "WK", base_price: 0.75, rating: 78, nationality: "AFG" },
  { name: "Shahidullah Kamal", role: "WK", base_price: 1.0, rating: 84, nationality: "AFG" },
  { name: "Litton Das", role: "BAT", base_price: 1.0, rating: 84, nationality: "BAN" },
  { name: "Najmul Hossain Shanto", role: "BAT", base_price: 0.5, rating: 76, nationality: "BAN" },
  { name: "Tanzid Hasan", role: "BAT", base_price: 0.75, rating: 80, nationality: "BAN" },
  { name: "Mahmudullah", role: "BAT", base_price: 1.0, rating: 82, nationality: "BAN" },
  { name: "Shakib Al Hasan", role: "BAT", base_price: 0.75, rating: 80, nationality: "BAN" },
  { name: "Towhid Hridoy", role: "BAT", base_price: 0.75, rating: 78, nationality: "BAN" },
  { name: "Soumya Sarkar", role: "BAT", base_price: 0.75, rating: 80, nationality: "BAN" },
  { name: "Naim Sheikh", role: "BAT", base_price: 1.5, rating: 86, nationality: "BAN" },
  { name: "Tamim Iqbal", role: "BAT", base_price: 1.0, rating: 82, nationality: "BAN" },
  { name: "Zakir Hasan", role: "BAT", base_price: 1.0, rating: 84, nationality: "BAN" },
  { name: "Mustafizur Rahman", role: "BOWL", base_price: 1.5, rating: 86, nationality: "BAN" },
  { name: "Taskin Ahmed", role: "BOWL", base_price: 1.0, rating: 84, nationality: "BAN" },
  { name: "Shoriful Islam", role: "BOWL", base_price: 0.75, rating: 80, nationality: "BAN" },
  { name: "Tanzim Hasan Sakib", role: "BOWL", base_price: 0.5, rating: 74, nationality: "BAN" },
  { name: "Hasan Mahmud", role: "BOWL", base_price: 0.75, rating: 80, nationality: "BAN" },
  { name: "Khaled Ahmed", role: "BOWL", base_price: 1.0, rating: 84, nationality: "BAN" },
  { name: "Nahid Rana", role: "BOWL", base_price: 1.5, rating: 86, nationality: "BAN" },
  { name: "Rishad Hossain", role: "BOWL", base_price: 1.5, rating: 88, nationality: "BAN" },
  { name: "Mehidy Hasan", role: "BOWL", base_price: 0.75, rating: 80, nationality: "BAN" },
  { name: "Taijul Islam", role: "BOWL", base_price: 1.0, rating: 84, nationality: "BAN" },
  { name: "Nasum Ahmed", role: "BOWL", base_price: 1.0, rating: 82, nationality: "BAN" },
  { name: "Mahedi Hasan", role: "AR", base_price: 1.0, rating: 82, nationality: "BAN" },
  { name: "Saifuddin", role: "AR", base_price: 0.75, rating: 78, nationality: "BAN" },
  { name: "Afif Hossain", role: "AR", base_price: 0.75, rating: 78, nationality: "BAN" },
  { name: "Mosaddek Hossain", role: "AR", base_price: 0.75, rating: 80, nationality: "BAN" },
  { name: "Yasir Ali", role: "AR", base_price: 0.5, rating: 74, nationality: "BAN" },
  { name: "Aminul Islam", role: "AR", base_price: 0.75, rating: 80, nationality: "BAN" },
  { name: "Mushfiqur Rahim", role: "WK", base_price: 1.0, rating: 82, nationality: "BAN" },
  { name: "Nurul Hasan", role: "WK", base_price: 0.75, rating: 80, nationality: "BAN" },
  { name: "Jaker Ali", role: "WK", base_price: 0.75, rating: 78, nationality: "BAN" },
  { name: "Anamul Haque", role: "WK", base_price: 0.75, rating: 80, nationality: "BAN" },
  { name: "Aditya Ranjan", role: "BAT", base_price: 0.3, rating: 72 },
  { name: "Arjun Anand", role: "BOWL", base_price: 0.3, rating: 72 },
  { name: "Anand Malhotra", role: "BAT", base_price: 0.3, rating: 70 },
  { name: "Parth Parikh", role: "BOWL", base_price: 0.3, rating: 68 },
  { name: "Sachin Khanna", role: "AR", base_price: 0.3, rating: 70 },
  { name: "Varun Singh", role: "AR", base_price: 0.3, rating: 70 },
  { name: "Ankit Kumar", role: "WK", base_price: 0.3, rating: 70 },
  { name: "Ishaan Patel", role: "AR", base_price: 0.5, rating: 76 },
  { name: "Shubham Joshi", role: "BOWL", base_price: 0.3, rating: 68 },
  { name: "Madhav Suri", role: "BOWL", base_price: 0.3, rating: 68 },
  { name: "Ayush Tripathi", role: "BAT", base_price: 0.3, rating: 72 },
  { name: "Aditya Bansal", role: "WK", base_price: 0.3, rating: 68 },
  { name: "Rakesh Ranjan", role: "BOWL", base_price: 0.5, rating: 76 },
  { name: "Yash Bhardwaj", role: "WK", base_price: 0.3, rating: 68 },
  { name: "Yuvraj Kulkarni", role: "BAT", base_price: 0.3, rating: 74 },
  { name: "Aman Trivedi", role: "AR", base_price: 0.3, rating: 72 },
  { name: "Ankit Pal", role: "BOWL", base_price: 0.3, rating: 72 },
  { name: "Sachin Sen", role: "BOWL", base_price: 0.3, rating: 66 },
  { name: "Saurabh Mishra", role: "BAT", base_price: 0.5, rating: 76 },
  { name: "Mohit Hazarika", role: "BOWL", base_price: 0.3, rating: 72 },
  { name: "Yash Kapoor", role: "AR", base_price: 0.3, rating: 70 },
  { name: "Aryan Chopra", role: "BAT", base_price: 0.3, rating: 68 },
  { name: "Shivam Phukan", role: "AR", base_price: 0.3, rating: 68 },
  { name: "Aditya Mondal", role: "BOWL", base_price: 0.3, rating: 70 },
  { name: "Karan Sahu", role: "AR", base_price: 0.3, rating: 68 },
  { name: "Yuvraj Chopra", role: "AR", base_price: 0.3, rating: 70 },
  { name: "Hitesh Naidu", role: "BOWL", base_price: 0.3, rating: 72 },
  { name: "Vikas Jain", role: "BAT", base_price: 0.3, rating: 70 },
  { name: "Sumit Chatterjee", role: "BOWL", base_price: 0.3, rating: 72 },
  { name: "Kartik Choudhary", role: "AR", base_price: 0.3, rating: 66 },
  { name: "Vivek Suri", role: "BOWL", base_price: 0.3, rating: 70 },
  { name: "Sahil Goswami", role: "BOWL", base_price: 0.3, rating: 72 },
  { name: "Mohit Bansal", role: "BAT", base_price: 0.3, rating: 72 },
  { name: "Hitesh Mittal", role: "BAT", base_price: 0.3, rating: 68 },
  { name: "Hemant Chauhan", role: "BAT", base_price: 0.3, rating: 72 },
  { name: "Yash Bhattacharya", role: "BAT", base_price: 0.3, rating: 70 },
  { name: "Hitesh Sood", role: "BOWL", base_price: 0.5, rating: 78 },
  { name: "Aadi Hazarika", role: "BAT", base_price: 0.3, rating: 68 },
  { name: "Anand Goswami", role: "BAT", base_price: 0.3, rating: 66 },
  { name: "Sumit Nair", role: "BAT", base_price: 0.5, rating: 76 },
  { name: "Shubham Basu", role: "AR", base_price: 0.3, rating: 72 },
  { name: "Anand Khanna", role: "BOWL", base_price: 0.3, rating: 68 },
  { name: "Ankit Choudhary", role: "WK", base_price: 0.3, rating: 70 },
  { name: "Anand Mishra", role: "BOWL", base_price: 0.3, rating: 72 },
  { name: "Nikhil Naidu", role: "BAT", base_price: 0.3, rating: 72 },
  { name: "Sachin Pattnaik", role: "WK", base_price: 0.3, rating: 68 },
  { name: "Tushar Wadhwa", role: "BOWL", base_price: 0.3, rating: 72 },
  { name: "Yash Anand", role: "BOWL", base_price: 0.3, rating: 70 },
  { name: "Ashwin Bhatia", role: "BAT", base_price: 0.3, rating: 72 },
  { name: "Arjun Tripathi", role: "BOWL", base_price: 0.3, rating: 70 },
  { name: "Eshan Sharma", role: "BAT", base_price: 0.3, rating: 72 },
  { name: "Shubham Sood", role: "BOWL", base_price: 0.3, rating: 72 },
  { name: "Naman Mukherjee", role: "BAT", base_price: 0.3, rating: 70 },
  { name: "Mayank Behera", role: "BAT", base_price: 0.3, rating: 68 },
  { name: "Sahil Joshi", role: "BOWL", base_price: 0.5, rating: 76 },
  { name: "Mohit Mehta", role: "BOWL", base_price: 0.3, rating: 72 },
  { name: "Nishant Mohapatra", role: "BAT", base_price: 0.3, rating: 68 },
  { name: "Naman Banerjee", role: "AR", base_price: 0.3, rating: 72 },
  { name: "Rohan Kapoor", role: "BAT", base_price: 0.3, rating: 72 },
  { name: "Arjun Mohapatra", role: "BOWL", base_price: 0.3, rating: 70 },
  { name: "Parth Pattnaik", role: "BAT", base_price: 0.3, rating: 70 },
  { name: "Vinay Behera", role: "BAT", base_price: 0.3, rating: 66 },
  { name: "Mohit Gogoi", role: "WK", base_price: 0.5, rating: 78 },
  { name: "Shubham Saha", role: "BAT", base_price: 0.3, rating: 74 },
  { name: "Hemant Nayak", role: "BOWL", base_price: 0.5, rating: 76 },
  { name: "Aryan Das", role: "BOWL", base_price: 0.3, rating: 74 },
  { name: "Atharv Tripathi", role: "BAT", base_price: 0.3, rating: 70 },
  { name: "Naman Choudhary", role: "BAT", base_price: 0.3, rating: 72 },
  { name: "Saurabh Pillai", role: "AR", base_price: 0.3, rating: 72 },
  { name: "Rohan Roy", role: "BAT", base_price: 0.3, rating: 70 },
  { name: "Varun Ghosh", role: "AR", base_price: 0.3, rating: 66 },
  { name: "Raghav Mondal", role: "BOWL", base_price: 0.3, rating: 68 },
  { name: "Jay Kapoor", role: "BOWL", base_price: 0.3, rating: 74 },
  { name: "Sanjay Sen", role: "BOWL", base_price: 0.5, rating: 76 },
  { name: "Kunal Tripathi", role: "BAT", base_price: 0.5, rating: 76 },
  { name: "Rohit Pillai", role: "BAT", base_price: 0.3, rating: 66 },
  { name: "Ayush Ghosh", role: "BAT", base_price: 0.3, rating: 74 },
  { name: "Divyansh Mondal", role: "WK", base_price: 0.3, rating: 72 },
  { name: "Mohit Prakash", role: "WK", base_price: 0.3, rating: 70 },
  { name: "Lakshya Mukherjee", role: "AR", base_price: 0.5, rating: 78 },
  { name: "Yuvraj Roy", role: "BOWL", base_price: 0.3, rating: 70 },
  { name: "Ankit Chopra", role: "AR", base_price: 0.3, rating: 68 },
  { name: "Pranav Pal", role: "AR", base_price: 0.3, rating: 74 },
  { name: "Nikhil Behera", role: "BAT", base_price: 0.3, rating: 66 },
  { name: "Divyansh Chatterjee", role: "BOWL", base_price: 0.3, rating: 72 },
  { name: "Vihaan Borah", role: "BOWL", base_price: 0.3, rating: 70 },
  { name: "Hitesh Jain", role: "BOWL", base_price: 0.5, rating: 76 },
  { name: "Rohit Kumar", role: "BOWL", base_price: 0.3, rating: 68 },
  { name: "Rakesh Vyas", role: "BAT", base_price: 0.3, rating: 70 },
  { name: "Akhil Deshpande", role: "WK", base_price: 0.3, rating: 74 },
  { name: "Ashwin Banerjee", role: "BOWL", base_price: 0.3, rating: 72 },
  { name: "Aadi Mehta", role: "BAT", base_price: 0.5, rating: 76 },
  { name: "Divyansh Iyer", role: "BOWL", base_price: 0.3, rating: 72 },
  { name: "Pranav Ranjan", role: "BOWL", base_price: 0.5, rating: 76 },
  { name: "Utkarsh Wadhwa", role: "BOWL", base_price: 0.3, rating: 74 },
  { name: "Sumit Borah", role: "WK", base_price: 0.3, rating: 72 },
  { name: "Naman Goel", role: "BAT", base_price: 0.3, rating: 66 },
  { name: "Ashwin Menon", role: "AR", base_price: 0.3, rating: 70 },
  { name: "Aditya Kumar", role: "BOWL", base_price: 0.3, rating: 72 },
  { name: "Pulkit Suri", role: "BAT", base_price: 0.3, rating: 66 },
  { name: "Rohit Phukan", role: "BOWL", base_price: 0.3, rating: 68 },
  { name: "Harsh Naidu", role: "BOWL", base_price: 0.3, rating: 68 },
  { name: "Kunal Mondal", role: "BOWL", base_price: 0.3, rating: 70 },
  { name: "Shivam Khanna", role: "WK", base_price: 0.3, rating: 68 },
  { name: "Shivam Sethi", role: "BOWL", base_price: 0.3, rating: 72 },
  { name: "Sanjay Trivedi", role: "BOWL", base_price: 0.3, rating: 68 },
  { name: "Sahil Khanna", role: "WK", base_price: 0.3, rating: 70 },
  { name: "Ravi Basu", role: "BOWL", base_price: 0.3, rating: 70 },
  { name: "Pulkit Gogoi", role: "BAT", base_price: 0.3, rating: 70 },
  { name: "Abhinav Ranjan", role: "BAT", base_price: 0.3, rating: 72 },
  { name: "Anand Pattnaik", role: "BAT", base_price: 0.3, rating: 72 },
  { name: "Pulkit Agarwal", role: "AR", base_price: 0.3, rating: 74 },
  { name: "Dev Menon", role: "BOWL", base_price: 0.3, rating: 72 },
  { name: "Nishant Banerjee", role: "WK", base_price: 0.3, rating: 72 },
  { name: "Chirag Pillai", role: "BAT", base_price: 0.3, rating: 70 },
  { name: "Sachin Tiwari", role: "WK", base_price: 0.3, rating: 70 },
  { name: "Raghav Bhattacharya", role: "BAT", base_price: 0.3, rating: 74 },
  { name: "Gaurav Khanna", role: "BOWL", base_price: 0.3, rating: 70 },
  { name: "Neeraj Parikh", role: "WK", base_price: 0.5, rating: 76 },
  { name: "Ansh Mehta", role: "AR", base_price: 0.3, rating: 70 },
  { name: "Rishabh Talukdar", role: "AR", base_price: 0.3, rating: 68 },
  { name: "Aadi Malhotra", role: "BOWL", base_price: 0.3, rating: 74 },
  { name: "Mayank Nayak", role: "BOWL", base_price: 0.3, rating: 70 },
  { name: "Rajat Nair", role: "BOWL", base_price: 0.3, rating: 72 },
  { name: "Vikas Gandhi", role: "BOWL", base_price: 0.3, rating: 70 },
  { name: "Ankit Ghosh", role: "WK", base_price: 0.3, rating: 68 },
  { name: "Rohit Joshi", role: "WK", base_price: 0.3, rating: 70 },
  { name: "Nikhil Mondal", role: "BAT", base_price: 0.5, rating: 76 },
  { name: "Utkarsh Shah", role: "BAT", base_price: 0.3, rating: 68 },
  { name: "Varun Prakash", role: "BOWL", base_price: 0.3, rating: 70 },
  { name: "Sachin Menon", role: "BOWL", base_price: 0.3, rating: 72 },
  { name: "Nakul Yadav", role: "AR", base_price: 0.3, rating: 72 },
  { name: "Sanjay Jain", role: "BOWL", base_price: 0.3, rating: 68 },
  { name: "Rajat Borah", role: "AR", base_price: 0.3, rating: 66 },
  { name: "Aniket Ranjan", role: "WK", base_price: 0.3, rating: 72 },
  { name: "Karan Mohapatra", role: "BAT", base_price: 0.5, rating: 76 },
  { name: "Piyush Bhardwaj", role: "WK", base_price: 0.3, rating: 66 },
  { name: "Jay Rao", role: "WK", base_price: 0.3, rating: 74 },
  { name: "Yash Saxena", role: "AR", base_price: 0.3, rating: 72 },
  { name: "Dhruv Mohapatra", role: "AR", base_price: 0.3, rating: 68 },
  { name: "Dhruv Deshpande", role: "BAT", base_price: 0.3, rating: 74 },
  { name: "Ayush Reddy", role: "BOWL", base_price: 0.3, rating: 74 },
  { name: "Kunal Behera", role: "BAT", base_price: 0.3, rating: 70 },
  { name: "Anand Deshpande", role: "BAT", base_price: 0.3, rating: 68 },
  { name: "Ankit Das", role: "AR", base_price: 0.3, rating: 72 },
  { name: "Yash Nair", role: "BOWL", base_price: 0.3, rating: 70 },
  { name: "Aman Saha", role: "BOWL", base_price: 0.3, rating: 68 },
  { name: "Aditya Gupta", role: "BAT", base_price: 0.3, rating: 72 },
  { name: "Sahil Nair", role: "WK", base_price: 0.3, rating: 74 },
  { name: "Ansh Naidu", role: "BOWL", base_price: 0.5, rating: 76 },
  { name: "Chirag Chopra", role: "BAT", base_price: 0.3, rating: 68 },
  { name: "Parth Wadhwa", role: "BOWL", base_price: 0.3, rating: 72 },
  { name: "Saurabh Pal", role: "WK", base_price: 0.3, rating: 72 },
  { name: "Ayush Goswami", role: "BOWL", base_price: 0.3, rating: 66 },
  { name: "Sarthak Goel", role: "AR", base_price: 0.3, rating: 68 },
  { name: "Rohan Prakash", role: "BOWL", base_price: 0.3, rating: 74 },
  { name: "Om Khanna", role: "AR", base_price: 0.3, rating: 70 },
  { name: "Shubham Rao", role: "BOWL", base_price: 0.3, rating: 68 },
  { name: "Samar Menon", role: "BAT", base_price: 0.3, rating: 66 },
  { name: "Chirag Talukdar", role: "AR", base_price: 0.3, rating: 70 },
  { name: "Vikas Doshi", role: "BAT", base_price: 0.5, rating: 76 },
  { name: "Sahil Singh", role: "BOWL", base_price: 0.3, rating: 70 },
  { name: "Pulkit Nair", role: "WK", base_price: 0.3, rating: 72 },
  { name: "Siddharth Agarwal", role: "BOWL", base_price: 0.3, rating: 68 },
  { name: "Vikas Suri", role: "AR", base_price: 0.3, rating: 70 },
  { name: "Kartik Anand", role: "BAT", base_price: 0.3, rating: 70 },
  { name: "Vikas Reddy", role: "AR", base_price: 0.5, rating: 76 },
  { name: "Mohit Reddy", role: "BOWL", base_price: 0.3, rating: 72 },
  { name: "Nishant Parikh", role: "BAT", base_price: 0.3, rating: 72 },
  { name: "Dhruv Phukan", role: "BOWL", base_price: 0.3, rating: 68 },
  { name: "Aditya Pillai", role: "BOWL", base_price: 0.3, rating: 66 },
  { name: "Sachin Mukherjee", role: "AR", base_price: 0.3, rating: 68 },
  { name: "Parth Phukan", role: "BAT", base_price: 0.3, rating: 70 },
  { name: "Divyansh Tripathi", role: "BOWL", base_price: 0.3, rating: 74 },
  { name: "Arjun Kapoor", role: "AR", base_price: 0.3, rating: 66 },
  { name: "Sanjay Prakash", role: "BOWL", base_price: 0.3, rating: 70 },
  { name: "Ayush Trivedi", role: "BAT", base_price: 0.3, rating: 74 },
  { name: "Yash Sen", role: "BOWL", base_price: 0.3, rating: 70 },
  { name: "Kartik Ranjan", role: "BOWL", base_price: 0.3, rating: 70 },
  { name: "Jay Khurana", role: "WK", base_price: 0.3, rating: 66 },
  { name: "Madhav Sood", role: "WK", base_price: 0.3, rating: 74 },
  { name: "Samar Tiwari", role: "BAT", base_price: 0.3, rating: 66 },
  { name: "Keshav Pal", role: "BAT", base_price: 0.3, rating: 72 },
  { name: "Pulkit Iyer", role: "BOWL", base_price: 0.3, rating: 72 },
  { name: "Samar Patel", role: "BOWL", base_price: 0.3, rating: 74 },
  { name: "Om Gogoi", role: "BOWL", base_price: 0.3, rating: 66 },
  { name: "Sachin Sood", role: "BOWL", base_price: 0.3, rating: 70 },
  { name: "Parth Pandey", role: "BAT", base_price: 0.3, rating: 66 },
  { name: "Raghav Pillai", role: "AR", base_price: 0.3, rating: 72 },
  { name: "Samar Behera", role: "BOWL", base_price: 0.3, rating: 68 },
  { name: "Kartik Doshi", role: "BOWL", base_price: 0.3, rating: 66 },
  { name: "Ayush Bhattacharya", role: "AR", base_price: 0.3, rating: 66 },
  { name: "Pratham Trivedi", role: "BOWL", base_price: 0.5, rating: 76 },
  { name: "Dhruv Jain", role: "AR", base_price: 0.3, rating: 74 },
  { name: "Harsh Pattnaik", role: "BAT", base_price: 0.3, rating: 68 },
  { name: "Ansh Tiwari", role: "BAT", base_price: 0.3, rating: 74 },
  { name: "Vivek Chatterjee", role: "WK", base_price: 0.3, rating: 72 },
  { name: "Parth Mittal", role: "BOWL", base_price: 0.3, rating: 74 },
  { name: "Sanjay Khurana", role: "BAT", base_price: 0.3, rating: 66 },
  { name: "Pulkit Pal", role: "AR", base_price: 0.3, rating: 72 },];
